### ISSUE TITLE
Fastest way to read vcf files 500MB - 2GB

### ISSUE THREAD

**Issue by alaingarcia** [zhoulab/SNP_Peggy#2]
Approximately 46,000 queries will need to be run.
I am currently building dictionaries that follow the format: {rsID: alleleFrequency}
I plan to then shelve the dictionaries for later use and querying.

I am doubtful whether or not this is the fastest choice to make the 46,000 queries because just making the dictionaries for ~25 vcf files that are 500MB - 2GB will take quite a long time. Making these dictionaries and shelving them would also take a large amount of space (easily several GB).

Any other suggestions or thoughts?

UPDATE: Building dictionaries takes longer than 6 hours (per chromosome) so this is not a good option. Will attempt to grep the 46,000 entries instead of building a library of possibly millions of entries.

UPDATE 2: grep is only fast for a few files. Really slow for others. The total size of vcf.gz files when decompressed: 795G. Compressed is 17G. Method should be able to search compressed files. zgrep method would take almost 90 hours. Will try BCFTools.

**Comment by victorlin** [comment]
Can you post the code you have to generate the dictionaries? Maybe it can be optimized a little. Also, how are you storing the dictionaries / data from grep?

**Comment by alaingarcia** [comment]
#gz files being worked with can be found at /ufrc/zhou/alaingarcia/1000genome/gz
import shelve
import vcf
import pandas as pd

"""Shelve module allows for storing of objects.
Declaration of new shelve "alleleFreqDB" with 'w' flag because 'alleleFreq.db' shelve file already existed in my case.
'c' flag can be used to create new shelve file though"""
alleleFreqDB = shelve.open('alleleFreq.db','w')

#Read csv with pandas
csvFile = pd.read_csv('N061_62_64_basedOn_Chr_Start.csv', low_memory = False)
rsNumbers = csvFile['avsnp147']

#Trying with just chromosome 1 before working with the rest
file = 'ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz'
chr1 = vcf.Reader(filename=file)

#Declare empty dict
alleleFreqDict = {}

#vcf reader allows for access to 'ID' fields, 'INFO' fields, etc.
for row in chr1:
	rsNumber = row.ID
#(row.INFO['AFR_AF'])[0] returns african allele frequency number
	afrAF = str((row.INFO['AFR_AF'])[0])

#makes the african allele freq accessible by rsID
	alleleFreqDict[rsNumber]=afrAF

#Stores dict in shelve as 'AFR'
alleleFreqDB['AFR'] = alleleFreqDict
alleleFreqDB.close()

**Comment by alaingarcia** [comment]
Shelve was being used to store dictionaries. It seems to work like a dictionary of objects. It stores the dictionary as a db.
For grep I never really got around to storing the data because it seemed too slow (around a minute or more) for some files. For 46,000 files, this would add up. 
If this shelve method doesn't end up working out, it looks like BCFTools and Tabix are promising for working with vcf.gz files. There are some complications with using those tools though.

**Comment by victorlin** [comment]
Here's a script using `awk` that works a lot faster than the PyVCF approach.

    awk '/^#/ { next } $3 != "." {print $3 "\t" substr($8, match($8, "AFR_AF") + 7, 6)}' <unzipped VCF file>

EDIT: formatted for better readability (not sure if this is correct line-breaking syntax for an `awk` script):

    /^#/ { next }
    $3 != "."
    {
        print $3
              "\t"
              substr($8, match($8, "AFR_AF") + 7, 6)
    }

**Comment by leizhou69** [comment]
Thanks.  Please give a brief explanation to this at today's meeting so 
we all can learn.

**Comment by alaingarcia** [comment]
I have sent a sbatch job to decompress all the files into /ufrc/zhou/alaingarcia/Decompress.
I have also sent another job to filter out the files using the awk method into /ufrc/zhou/alaingarcia/Filtered.
This awk method has proven to be extremely quick, thank you Victor.
