### ISSUE TITLE
links and brief intro

### ISSUE THREAD

**Issue by leizhou69** [zhoulab/SNP_Peggy#3]
Alain,
Could you
1.) write a brief intro as to what value was extract for the AFR_AF column (1-2 sentence).
2.) test to see if the hyperlink works when the file is opened in excel. - I tried it and for some reason there as not hyperlink for the rs# on the "links" column.

Thanks a lot,
Lei

**Comment by alaingarcia** [comment]
The links were opening in excel, but after uploading and downloading the file, the links seem to have been stripped away. Will look into this.

**Comment by alaingarcia** [comment]
The issue was caused by Excel removing hyperlinks when being saved as a .csv. I bypassed this and it should now work. Let me know if there are still any issues.

I will write the brief intro on the github README.md

**Comment by alaingarcia** [comment]
Brief intro has been added.
